// Mock data for the Literature Review page
// Kept separate from components per Frontend Development Guidelines

export interface LibraryPaper {
  id: string;
  title: string;
  authors: string;
  journal?: string;
  tags?: string[];
  checked?: boolean;
}

export const mockLibraryPapers: LibraryPaper[] = [
  {
    id: 'p-1',
    title: 'Quantum Supremacy Benchmarks (2023)',
    authors: 'Jones, R. &bull; Nature Quantum',
    tags: ['Quantum', 'Benchmarking'],
    checked: true,
  },
  {
    id: 'p-2',
    title: 'Error Correction Advancements',
    authors: 'Silva, L. &bull; PRL',
    tags: ['Fault Tolerance'],
    checked: true,
  },
  {
    id: 'p-3',
    title: 'Large Language Models in Bio-Research',
    authors: 'Gomez, M. &bull; arXiv',
    tags: ['AI', 'Biology'],
    checked: false,
  },
  {
    id: 'p-4',
    title: 'Scalability of NISQ Devices',
    authors: 'Wang, T. &bull; IEEE',
    checked: true,
  },
  {
    id: 'p-5',
    title: 'Neural Architecture Search Efficiency',
    authors: 'Zhu, F. &bull; ICML',
    checked: false,
  },
  {
    id: 'p-6',
    title: 'Cryogenic Cooling Efficiency',
    authors: 'Patel, K. &bull; Oxford',
    checked: true,
  },
  {
    id: 'p-7',
    title: 'Federated Learning Constraints',
    authors: 'Lee, D. &bull; KDD',
    checked: false,
  },
];

export interface SynthesisTheme {
  title: string;
  description: string;
}

export const mockSynthesisReport = {
  title: 'Current Trajectory of NISQ-era Quantum Computing and Scalability Constraints',
  meta: 'A comprehensive literature synthesis generated by Anveshak AI on Oct 24, 2024.',
  introduction: 'The landscape of quantum computing has shifted significantly from theoretical speculations to experimental validation. Current research focuses on Noisy Intermediate-Scale Quantum (NISQ) devices, which represent the immediate frontier of computational physics. This review synthesizes findings from four seminal works to outline the state of error correction, scalability, and thermodynamic efficiency in cryogenic environments.',
  themes: [
    {
      title: 'Error Mitigation Over Correction',
      description: 'All reviewed papers prioritize algorithmic error mitigation techniques over full hardware-based fault tolerance, noting that current qubit fidelities remain below the required thresholds for surface code implementation.'
    },
    {
      title: 'Thermal Management',
      description: 'A recurrent bottleneck identified is the heat dissipation within dilution refrigerators. Scalability is directly proportional to our ability to minimize thermal noise from interconnects.'
    }
  ] as SynthesisTheme[],
  methods: [
    {
      name: 'Monte Carlo Simulations',
      desc: 'Used by Smith et al. to predict qubit behavior under varying noise densities.'
    },
    {
      name: 'Experimental Benchmarking',
      desc: 'Real-world testing on the Eagle-2 processor to validate circuit depth limitations.'
    },
    {
      name: 'Comparative Taxonomy',
      desc: 'Systematic analysis of cryogenic versus room-temperature control electronics.'
    }
  ],
  findingQuote: 'The plateau in qubit coherence times suggests a fundamental limitation in current superconducting materials, rather than just environmental noise.',
  findingAnalysis: 'Analysis indicates a 40% improvement in error-suppression when utilizing hybrid quantum-classical loops. Furthermore, cryogenic power budgets are currently the limiting factor for systems exceeding 1,000 qubits.',
  futureDirections: 'Future research must pivot towards topological insulators and photonics-integrated control systems to bypass the thermal dissipation limit. Inter-disciplinary collaboration between material scientists and computer architects will be paramount in the next decade of development.',
  sources: [
    '[1] Jones, R. (2023). Quantum Benchmarking in NISQ systems. Nature Quantum.',
    '[2] Silva, L. & Chen, X. (2024). Error Mitigation in Superconducting Circuits. Physical Review Letters.',
    '[3] Wang, T. et al. (2023). Scalability Bottlenecks in Cryogenic Environments. IEEE Nano.',
    '[4] Patel, K. (2024). Advanced NISQ Architectures. Oxford Press.'
  ]
};
